localsights/maps/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("home", HomeView.as_view(), name='home'),
    path("maps", MapView.as_view(), name='maps'),
    path("geocoding/<int:pk>", GeocodingView.as_view(), name='geocoding'),
    path("distance", DistanceView.as_view(), name='distance'),
    path("display_map", DisplayMapView.as_view(), name='display_map'),
    
]

localsights/maps/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns
import uuid # Required for unique location instances


class Location(models.Model):
    name = models.CharField(max_length=500)
    creator = models.CharField(
        max_length=200,
        unique=False,
        help_text="",
        default=''
    )
    address = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    edited_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    lat = models.DecimalField(max_digits = 9, decimal_places = 6, blank=True, null=True) 
    lng = models.DecimalField(max_digits = 9, decimal_places = 6, blank=True, null=True) 
    place_id = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('location-detail', args=[str(self.id)])
    
    def __eq__(self, other): 
        if isinstance(other, Location): 
            if other.name == self.name and self.address == other.address and self.city == other.city and self.zipcode == other.zipcode: 
                return True
        return False
    
    def __hash__(self):
        return super().__hash__()
    
class Map(models.Model):

    name = models.CharField(
        max_length=200,
        unique=False,
        help_text="",
        default=''
    )

    creator = models.CharField(
        max_length=200,
        unique=False,
        help_text="",
        default=''
    )

    starting_location = models.ForeignKey(Location, on_delete=models.CASCADE, default='', null=True, related_name='firstlocation')
    dest_location = models.ForeignKey(Location, on_delete=models.CASCADE, default='', null=True, related_name='lastlocation')

    locations = models.ManyToManyField(
        'Location',
        related_name='locations'
    )

    date = models.DateField()

    zoom_level = models.FloatField()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('map-detail', args=[str(self.id)])
    
class Distances (models.Model):
    from_location = models.ForeignKey(Location, related_name = 'from_location', on_delete=models.CASCADE)
    to_location = models.ForeignKey(Location, related_name = 'to_location', on_delete=models.CASCADE)
    mode = models.CharField(max_length=200, blank=True, null=True)
    distance_km = models.DecimalField(max_digits=10, decimal_places=2)
    duration_mins = models.DecimalField(max_digits=10, decimal_places=2)
    duration_traffic_mins = models.DecimalField(max_digits=10, decimal_places=2,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True,blank=True, null=True)
    edited_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id

localsights/maps/forms.py
from django import forms
from .models import *
from django.forms import ModelForm

modes = (
    ("driving", "driving"), 
    ("walking", "walking"),
    ("bicycling", "bicycling"),
    ("transit", "transit")
)

class createMapForm(forms.Form):
    class Meta:
        model = Map
        fields = '__all__'



class DistanceForm(ModelForm): 
    from_location = forms.ModelChoiceField(label="Location from", required=True, queryset=Location.objects.all())
    to_location = forms.ModelChoiceField(label="Location to", required=True, queryset=Location.objects.all())
    mode = forms.ChoiceField(choices=modes, required=True)
    class Meta: 
        model = Distances
        exclude = ['created_at', 'edited_at', 'distance_km','duration_mins','duration_traffic_mins']

localsights/maps/views.py
import json
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
import googlemaps
from django.conf import settings
from .forms import *
from datetime import datetime
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import PermissionRequiredMixin
import requests
from .models import __eq__

class HomeView(ListView):
    template_name = "pages/home.html"
    context_object_name = 'mydata'
    model = Location
    success_url = "/"


class GeocodingView(View):
    template_name = "pages/geocoding.html"

    def get(self,request,pk): 
        location = Location.objects.get(pk=pk)

        if location.lng and location.lat and location.place_id != None: 
            lat = location.lat
            lng = location.lng
            place_id = location.place_id
            label = "from my database"

        if location.address and location.country and location.zipcode and location.city != None: 
            address_string = str(location.address)+", "+str(location.zipcode)+", "+str(location.city)+", "+str(location.country)
            key = getattr(settings, 'GOOGLE_API_KEY', None)
            gmaps = googlemaps.Client(key)
            result = gmaps.geocode(address_string)[0]
            
            lat = result.get('geometry', {}).get('location', {}).get('lat', None)
            lng = result.get('geometry', {}).get('location', {}).get('lng', None)
            place_id = result.get('place_id', {})
            label = "from my api call"
            location.lat = lat
            location.lng =  lng
            location.place_id = place_id
            location.save()

        else: 
            result = ""
            lat = ""
            lng = ""
            place_id = ""
            label = "no call made"


        context = {
            'result':result,
            'location':location,
            'lat':lat, 
            'lng':lng, 
            'place_id':place_id, 
            'label':label
        }
        
        return render(request, self.template_name, context)
    
class DistanceView(View):
    template_name = "pages/distance.html"

    def get(self, request): 
        form = DistanceForm
        distances = Distances.objects.all()
        context = {
            'form':form,
            'distances':distances
        }

        return render(request, self.template_name, context)

    def post(self, request): 
        form = DistanceForm(request.POST)
        if form.is_valid(): 
            from_location = form.cleaned_data['from_location']
            from_location_info = Location.objects.get(name=from_location)
            from_address_string = str(from_location_info.address)+", "+str(from_location_info.zipcode)+", "+str(from_location_info.city)+", "+str(from_location_info.country)

            to_location = form.cleaned_data['to_location']
            to_location_info = Location.objects.get(name=to_location)
            to_address_string = str(to_location_info.address)+", "+str(to_location_info.zipcode)+", "+str(to_location_info.city)+", "+str(to_location_info.country)

            mode = form.cleaned_data['mode']
            now = datetime.now()
            key = getattr(settings, 'GOOGLE_API_KEY', None)
            gmaps = googlemaps.Client(key)
            calculate = gmaps.distance_matrix(
                    from_address_string,
                    to_address_string,
                    mode = mode,
                    departure_time = now
            )


            duration_seconds = calculate['rows'][0]['elements'][0]['duration']['value']
            duration_minutes = duration_seconds/60

            distance_meters = calculate['rows'][0]['elements'][0]['distance']['value']
            distance_kilometers = distance_meters/1000

            if 'duration_in_traffic' in calculate['rows'][0]['elements'][0]: 
                duration_in_traffic_seconds = calculate['rows'][0]['elements'][0]['duration_in_traffic']['value']
                duration_in_traffic_minutes = duration_in_traffic_seconds/60
            else: 
                duration_in_traffic_minutes = None

            
            obj = Distances(
                from_location = Location.objects.get(name=from_location),
                to_location = Location.objects.get(name=to_location),
                mode = mode,
                distance_km = distance_kilometers,
                duration_mins = duration_minutes,
                duration_traffic_mins = duration_in_traffic_minutes
            )

            obj.save()

        else: 
            print(form.errors)
        
        return redirect('distance')
    
class DisplayMapView(View): 
    template_name = "pages/display_map.html"
    apikey = getattr(settings, 'GOOGLE_API_KEY', None)
    def get(self,request): 
        context = {
            "key": DisplayMapView.apikey
        }

        return render(request, self.template_name, context)
    
class LocationListView(ListView):
    model = Location
    template_name = "pages/locations.html"
    
    def get_queryset(self):
        return (
            Location.objects.filter(creator=self.request.user)
        )

class LocationDetailView(DetailView):
    model = Location
    template_name = "locations/location_detail.html"

    def get(self, request, pk):
        location = Location.objects.get(pk=pk)
        
        
        # Once we have the address use it to get latitude and longitude from the API 
        if (location.address and location.country and location.zipcode and location.city != None) and (location.lat == None or location.lng == None or location.place_id == None): 
            print("here in detail view")
            address_string = str(location.address)+", "+str(location.zipcode)+", "+str(location.city)+", "+str(location.country)
            key = getattr(settings, 'GOOGLE_API_KEY', None)
            gmaps = googlemaps.Client(key)
            result = gmaps.geocode(address_string)[0]
            
            location.lat = result.get('geometry', {}).get('location', {}).get('lat', None)
            location.lng = result.get('geometry', {}).get('location', {}).get('lng', None)
            location.place_id = result.get('place_id', {})
        location.creator = str(self.request.user)

        location.save()
        context = {
            "location": location
        }
        return render(request, self.template_name, context)

class LocationCreateView(CreateView):
    model = Location
    fields = ['name', 'zipcode', 'city', 'country', 'address']
    template_name = "locations/location_form.html"
    #permission_required = 'location.add_location'

class LocationUpdateView(UpdateView):
    model = Location
    # Not recommended (potential security issue if more fields added)
    fields = ['name', 'zipcode', 'city', 'country', 'address']
    template_name = "locations/location_form.html"
    #permission_required = 'location.change_location'


class LocationDeleteView(DeleteView):
    model = Location
    success_url = reverse_lazy('locations')
    template_name = "locations/location_confirm_delete.html"
    #permission_required = 'location.delete_location'

    def form_valid(self, form):
        try:
            self.object.delete()
            return render(self.success_url)
        except Exception as e:
            return render(
                reverse("location-delete", kwargs={"pk": self.object.pk})
            )
        

class MapListView(ListView):
    model = Map
    template_name = "pages/maps.html"

    def get_queryset(self):
        return (
            Map.objects.filter(creator=self.request.user)
        )

class MapDetailView(DetailView):
    model = Map

    template_name = "maps/map_detail.html"
    apikey = getattr(settings, 'GOOGLE_API_KEY', None)
        
    def get(self, request, pk): 
        # Get the map and its locations
        map = Map.objects.get(pk=pk)
        map_locations = map.locations.all()

        map.creator = str(self.request.user)
        map.save()
        
        # Generate the starting point, waypoints and destination parrameters for API call
        origin = f'{map.starting_location.lat},{map.starting_location.lng}'
        dest = f'{map.dest_location.lat},{map.dest_location.lng}'
        way_points = []
        for location in map_locations:
            # check to make sure this isn't the starting or end point
            print("In for loop")
            if location != map.starting_location and location != map.dest_location:
                print("Location name: ", location.name)
                way_points.append(f'{location.lat},{location.lng}')

        print("origin: ", origin)
        print()
        print("way_points: ", way_points)
        print()
        print("dest: ", dest)


        locations = []        
        address_string = ""
        apikey = getattr(settings, 'GOOGLE_API_KEY', None)
        print("map_locations: ", map_locations)
        
      #  buildPath(self, request, pk)
        for location in map_locations:          
            data = {
                'lat': float(location.lat),
                'lng': float(location.lng),
                'name': location.name
            }
            locations.append(data)

        origin = json.dumps(origin)
        way_points = json.dumps(way_points)
        dest = json.dumps(dest)

        context = {
            "map": map,
            "origin": origin,
            "way_points": way_points,
            "dest": dest,
            'address': address_string,
            "key": MapDetailView.apikey
        }

        return render(request, self.template_name, context)
        

class MapCreateView(CreateView):
    model = Map
    #fields = ['name', 'starting_location', 'dest_location', 'locations']
    template_name = "maps/map_form.html"

    def get(self, request):
        context = {

localsights/templates/pages/about.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "About" %}{% endblock %}

{% block inner %}

<style>
  /* Add your custom styles here to match the theme */

  body {
    background: linear-gradient(to bottom,  #002466, #929191);
    color: #fff;
    margin: 0;
    font-family: 'Consolas', serif;
    overflow-x: hidden; /* Prevent horizontal scrolling */
  }

  .container {
    padding: 1vw;
    text-align: left;
  }

  h1 {
    font-size: 4vw;
    font-weight: bold;
    margin-bottom: 20px;
  }

  p {
    font-size: 1.2em;
    line-height: 1.6;
    margin-bottom: 20px;
  }

  .about-section {
    margin-top: 20px;
  }

  .about-section h2 {
    font-size: 2em;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .about-section p {
    font-size: 1em;
    line-height: 1.4;
    margin-bottom: 15px;
  }

  .button {
    background: #fff;
    border: none;
    padding: 10px 20px;
    font-size: 15px;
    font-weight: 600;
    text-transform: uppercase;
    cursor: pointer;
    transform: skew(-21deg);
    margin-top: 20px; /* Add margin for spacing */
  }

  .button::before {
    content: '';
    position: absolute;
    top: 0;
    bottom: 0;
    right: 100%;
    left: 0;
    opacity: 0;
    z-index: -1;
    transition: all 0.5s;
  }

  .button:hover::before {
    left: 0;
    right: 0;
    opacity: 1;
  }
</style>

<div class="container">
  <h1>{% trans "About Our Project" %}</h1>

  <div class="about-section">
    <h2>{% trans "Project Overview" %}</h2>
    <p>{% trans "Localsights is a website designed to revolutionize travel planning by harnessing the power of the Traveling Salesman Problem (TSP) algorithm. Users can input their desired locations, and our platform calculates the most efficient routes, creating optimized maps for their journeys. From scenic road trips to efficient city tours, Localsights ensures that every adventure is mapped out for maximum enjoyment and convenience!" %}</p>
  </div>

  <div class="about-section">
    <h2>{% trans "Team Members" %}</h2>
    <p>Brock Redman</p>
    <p>Nischal Lawot</p>
    <p>Colin Gregory</p>
  </div>

  <div class="about-section">
    <h2>{% trans "Technologies Used" %}</h2>
    <p>
      <strong>Framework:</strong> Django<br>
      <strong>Languages:</strong> Python, HTML, CSS, JavaScript<br>
      <strong>Database:</strong> PostgreSQL<br>
      <strong>Mapping Services:</strong> Google Maps API<br>
      <strong>Deployment:</strong> Digital Ocean<br>
      <strong>Version Control:</strong> Git, GitHub
    </p>
  </div>

  <a href="{% url 'home' %}" class="button">{% trans "Back to Home" %}</a>
</div>

{% endblock %}

localsights/templates/pages/distance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static i18n %}

{% block title %}localsights{% endblock title %}

{% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <!-- Your specific CSS file for the maps page -->
    <link href="{% static 'css/maps.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="pageholder">
    <div class="titleholder"> 
        
        <div class="title"> Temp distances only using 2 locations! </div> 
        
    </div>


    <div class="linkholder">
        {% if distances.count == 0 %}
            <div> No data available </div>
        {% else %}
            <table id="ourtable3" class="myTable m-3">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>From Location</th>
                        <th>To Location</th>
                        <th>Mode</th>
                        <th>Distance in km</th>
                        <th>Duration in mins</th>
                        <th>Duration traffic in mins</th>
                       
                    </tr>
                </thead>

                <tbody>
                    {% for a in distances %}
                    <tr>
                        <td> {{a.id}} </td>
                        <td> {{a.from_location}} </td>
                        <td> {{a.to_location}} </td>
                        <td> {{a.mode}} </td>
                        <td> {{a.distance_km}} </td>
                        <td> {{a.duration_mins}} </td>
                        <td> {{a.duration_traffic_mins}} </td>
                       
                    </tr>

                    {% endfor%}
                </tbody>

                
            </table>
        {% endif %}
        
     </div>

    <form method="post">
        {% csrf_token %}
        <div class="linkholder"> 
            
            <div class="form1 ml-3"> {{form.from_location|as_crispy_field}} </div>
            <div class="form1 ml-3"> {{form.to_location|as_crispy_field}} </div>
            <div class="form1 ml-3"> {{form.mode|as_crispy_field}} </div>

            <button class="ourbutton" type="submit"> Submit </button>


        </div>
    </form>

</div>


{% endblock %}

localsights/templates/pages/geocoding.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}localsights{% endblock title %}

{% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <!-- Your specific CSS file for the maps page -->
    <link href="{% static 'css/maps.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="pageholder">
    <div class="titleholder"> 
        <div class="title"> Geocoding template for {{ location.name }} </div> 
    </div>

    <div class="linkholder">
        <table id="ourtable3" class="myTable m-3">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Zipcode</th>
                    <th>City</th>
                    <th>Country</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Place ID</th>
                    
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>{{ location.id }}</td>
                    <td>{{ location.name }}</td>
                    <td>{{ location.address }}</td>
                    <td>{{ location.zipcode }}</td>
                    <td>{{ location.city }}</td>
                    <td>{{ location.country }}</td>

                    <td>{{ lat }}</td>
                    <td>{{ lng }}</td>
                    <td>{{ place_id }}</td>
                    
                    
                </tr>
            </tbody>
        </table>
    </div>
    <div class="linkholder">
        {{lat}}
    </div>
</div>

{% endblock content %}

localsights/templates/pages/locations.html
{% extends "base.html" %}

{% block content %}
<style>
    body {
        background: linear-gradient(to bottom, #002466, #ffffff);
        color: #fff;
        margin: 0;
        font-family: 'Consolas', serif;
        overflow-x: hidden; /* Prevent horizontal scrolling */
    }

    .container {
        padding: 2vw;
        text-align: left;
    }

    .location-link {
        color: white;
    }
    h1 {
        top: 1vw;
        left: 10%;
        font-size: 4vw;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .button {
        background: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 15px;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        transform: skew(-21deg);
        margin-top: 20px; /* Add margin for spacing */
    }

    .span {
        display: inline-block;
        transform: skew(21deg);
    }

    .button::before {
        content: '';
        position: absolute;
        top: 0;
        bottom: 0;
        right: 100%;
        left: 0;
        background: #002466;
        opacity: 0;
        z-index: -1;
        transition: all 0.5s;
    }

    .button:hover {
        color: #fff;
    }

    .button:hover::before {
        left: 0;
        right: 0;
        opacity: 1;
    }

    .location-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 30px; /* Add margin for spacing */
        left: 5%;
    }

    .location-table th, .location-table td {
        padding: 1vw;
        border-bottom: 1px solid #fff;
        text-align: left;
    }

    .location-table th {
        background-color: #002466;
        color: #fff;
    }

    .location-table tbody tr:nth-child(even) {
        background-color: #555555;
    }

    .location-buttons a {
        margin-right: 10px; /* Add margin between buttons */
    }

    .location-buttons a.btn-primary,
    .location-buttons a.btn-danger {
        background: transparent;
        color: #fff;
        border: 1px solid #fff;
        padding: 5px 10px;
        font-size: 14px;
        text-transform: uppercase;
        cursor: pointer;
        border-radius: 3px;
        transition: background-color 0.3s ease, color 0.3s ease;
    }

  
    .location-buttons a.btn-danger:hover {
        background-color: #f77a7a;
        color: #fafafa;
    }

    .location-buttons a.btn-primary:hover{
        background-color: #6e82f5;
        color: #fafafa;
    }

</style>

<div class="container">
    <h1>Your Locations</h1>

    <table class="location-table">
        <tr>
            <th>Name</th>
            <th>Zipcode</th>
            <th>City</th>
            <th>Country</th>
            <th>Address</th>
            <th> </th>
        </tr>

        {% if location_list %}
        <tbody>
            {% for location in location_list %}
            <tr>
                <th>{{ location.name }}</th>
                <td>{{ location.zipcode }}</td>
                <td>{{ location.city }}</td>
                <td>{{ location.country }}</td>
                <td>{{ location.address }}</td>
                <td class="location-buttons">
                    <a href="{% url 'location-update' location.id %}" class="btn btn-primary">Update</a>
                    <a href="{% url 'location-delete' location.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        {% else %}
        </table>
        <p>There are no locations yet.</p>
        {% endif %}
        <a href="{% url 'location-create' %}">
          <button type="button" class="button">Create Location +</button>
      </a>
</div>
{% endblock %}

localsights/templates/pages/maps.html
{% extends "base.html" %}

{% block content %}
<style>
    body {
        background: linear-gradient(to bottom, #002466, #ffffff);
        color: #fff;
        margin: 0;
        font-family: 'Consolas', serif;
        overflow-x: hidden; /* Prevent horizontal scrolling */
    }

    .container {
        padding-bottom: 20vw;
        padding: 2vw;
        text-align: left;
    }

    h1 {
        top: 1vw;
        left: 10%;
        font-size: 4vw;
        font-weight: bold;
        margin-bottom: 20px;
    }

    .button {
        background: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 15px;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        transform: skew(-21deg);
        margin-top: 20px; /* Add margin for spacing */
    }

    .span {
        display: inline-block;
        transform: skew(21deg);
    }

    .button::before {
        content: '';
        position: absolute;
        top: 0;
        bottom: 0;
        right: 100%;
        left: 0;
        background: #002466;
        opacity: 0;
        z-index: -1;
        transition: all 0.5s;
    }

    .button:hover {
        color: #fff;
    }

    .button:hover::before {
        left: 0;
        right: 0;
        opacity: 1;
    }

    .location-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 30px; /* Add margin for spacing */
        left: 5%;
    }

    .location-table th{
        padding: 1vw;
        border-bottom: 1px solid #fff;
        text-align: left;
        background-color: #002466;
    }

    .location-table td {
        padding: 1vw;
        border-bottom: 1px solid #fff;
        text-align: left;
    }

    .location-table tbody tr:nth-child(even) {
        background-color: #555555;
    }

    .location-buttons a {
        margin-right: 10px; /* Add margin between buttons */
    }

    .location-buttons a.btn-primary,
    .location-buttons a.btn-danger {
        background: transparent;
        color: #fff;
        border: 1px solid #fff;
        padding: 5px 10px;
        font-size: 14px;
        text-transform: uppercase;
        cursor: pointer;
        border-radius: 3px;
        transition: background-color 0.3s ease, color 0.3s ease;
    }


  
    .location-buttons a.btn-danger:hover {
        background-color: #f77a7a;
        color: #fafafa;
    }

    .location-buttons a.btn-primary:hover{
        background-color: #6e82f5;
        color: #fafafa;
    }

</style>

<div class="container">
    <h1>Your Maps</h1>
    <p>Click on your map name to view directions!</p>

    <table class="location-table">
        <tr>
            <th>Name</th>
            <th>Creator</th>
            <th>Zoom Level</th>
            <th>Date</th>
            <th>  </th>
        </tr>

        {% if map_list %}
        <tbody>
            {% for map in map_list %}
            <tr>
                <td><a href="{{ map.get_absolute_url }}">{{ map.name }}</a></td>
                <td>{{ map.creator }}</td>
                <td>{{ map.zoom_level }}</td>
                <td>{{ map.date }}</td>
                <td class="location-buttons">
                    <a href="{% url 'map-update' map.id %}" class="btn btn-primary">Update</a>
                    <a href="{% url 'map-delete' map.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        {% else %}
        </table>
        <p>There are no maps yet.</p>
        {% endif %}
        <a href="{% url 'map-create' %}">
          <button type="button" class="button">Create Map +</button>
      </a>
</div>
{% endblock %}