localsights/maps/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("home", HomeView.as_view(), name='home'),
    path("maps", MapView.as_view(), name='maps'),
    path("geocoding/<int:pk>", GeocodingView.as_view(), name='geocoding'),
    path("distance", DistanceView.as_view(), name='distance'),
    path("display_map", DisplayMapView.as_view(), name='display_map'),
    
]

localsights/users/urls.py
from django.urls import path

from localsights.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

localsights/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}localsights{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
  <!-- Latest compiled and minified Bootstrap CSS -->
  <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

  <!-- Your stuff: Third-party CSS libraries go here -->
  <!-- This file stores project-specific CSS -->

  <!-- <link href="{% static 'css/project.css' %}" rel="stylesheet"> -->
  {% endblock %}

  <style>

/* Navbar container styling */
.navbar {
  background: transparent;
}

/* Flex container for navbar items */
.navbar-nav {
  top: 0vw;
  text-decoration: none; 
  list-style-type: none;
  display: flex;
  justify-content: left; /* Distribute items evenly along the main axis */
  align-items: center; /* Center items vertically */
}

/* Navbar brand styling */
.navbar-brand {
  display: none;
}

/* Navbar link styling */
.navbar-nav .nav-link {
  text-decoration: none; 
  color: white !important; /* Change navbar link text color */
  font-size: 18px; /* Adjust navbar link font size */
  padding: 2vw;
}

/* Navbar link hover styling */
.navbar-nav .nav-link:hover {
  text-decoration: none; 
  color: #ccc !important; /* Change navbar link text color on hover */
}

  </style>
</head>

<body>

  
    <nav class="navbar navbar-expand-md navbar-dark bg-dark" style="padding: 10px 20px;">
      
      <!-- <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> -->
      <a class="navbar-brand" href="{% url 'home' %}" style="font-size: 24px;">localsights</a>
  
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto" style="font-size: 18px;">
          
          {% if request.user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only"></span></a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'maps' %}">Maps</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'locations' %}">Locations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
            </li>
          {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  

  <div class="container">

    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %}
    {% endif %}

    {% block content %}
    <p>The Ultimate Cheese Index! This text is inherited on other pages!</p>
    {% endblock content %}

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

  <!-- Le javascript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}
  <!-- Bootstrap JS and its dependencies-->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->
  <script src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}
</body>
</html>

 