localsights/maps/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("home", HomeView.as_view(), name='home'),
    path("maps", MapView.as_view(), name='maps'),
    path("geocoding/<int:pk>", GeocodingView.as_view(), name='geocoding'),
    path("distance", DistanceView.as_view(), name='distance'),
    path("display_map", DisplayMapView.as_view(), name='display_map'),
    
]

localsights/maps/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns
import uuid # Required for unique location instances


class Location(models.Model):
    name = models.CharField(max_length=500)
    creator = models.CharField(
        max_length=200,
        unique=False,
        help_text="",
        default=''
    )
    address = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    country = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    edited_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    lat = models.DecimalField(max_digits = 9, decimal_places = 6, blank=True, null=True) 
    lng = models.DecimalField(max_digits = 9, decimal_places = 6, blank=True, null=True) 
    place_id = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('location-detail', args=[str(self.id)])
    
    def __eq__(self, other): 
        if isinstance(other, Location): 
            if other.name == self.name and self.address == other.address and self.city == other.city and self.zipcode == other.zipcode: 
                return True
        return False
    
    def __hash__(self):
        return super().__hash__()
    
class Map(models.Model):

    name = models.CharField(
        max_length=200,
        unique=False,
        help_text="",
        default=''
    )

    creator = models.CharField(
        max_length=200,
        unique=False,
        help_text="",
        default=''
    )

    starting_location = models.ForeignKey(Location, on_delete=models.CASCADE, default='', null=True, related_name='firstlocation')
    dest_location = models.ForeignKey(Location, on_delete=models.CASCADE, default='', null=True, related_name='lastlocation')

    locations = models.ManyToManyField(
        'Location',
        related_name='locations'
    )

    date = models.DateField()

    zoom_level = models.FloatField()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('map-detail', args=[str(self.id)])
    
class Distances (models.Model):
    from_location = models.ForeignKey(Location, related_name = 'from_location', on_delete=models.CASCADE)
    to_location = models.ForeignKey(Location, related_name = 'to_location', on_delete=models.CASCADE)
    mode = models.CharField(max_length=200, blank=True, null=True)
    distance_km = models.DecimalField(max_digits=10, decimal_places=2)
    duration_mins = models.DecimalField(max_digits=10, decimal_places=2)
    duration_traffic_mins = models.DecimalField(max_digits=10, decimal_places=2,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True,blank=True, null=True)
    edited_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id

localsights/maps/forms.py
from django import forms
from .models import *
from django.forms import ModelForm

modes = (
    ("driving", "driving"), 
    ("walking", "walking"),
    ("bicycling", "bicycling"),
    ("transit", "transit")
)

class createMapForm(forms.Form):
    class Meta:
        model = Map
        fields = '__all__'



class DistanceForm(ModelForm): 
    from_location = forms.ModelChoiceField(label="Location from", required=True, queryset=Location.objects.all())
    to_location = forms.ModelChoiceField(label="Location to", required=True, queryset=Location.objects.all())
    mode = forms.ChoiceField(choices=modes, required=True)
    class Meta: 
        model = Distances
        exclude = ['created_at', 'edited_at', 'distance_km','duration_mins','duration_traffic_mins']

localsights/maps/views.py
import json
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
import googlemaps
from django.conf import settings
from .forms import *
from datetime import datetime
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import PermissionRequiredMixin
import requests
from .models import __eq__

class HomeView(ListView):
    template_name = "pages/home.html"
    context_object_name = 'mydata'
    model = Location
    success_url = "/"


class GeocodingView(View):
    template_name = "pages/geocoding.html"

    def get(self,request,pk): 
        location = Location.objects.get(pk=pk)

        if location.lng and location.lat and location.place_id != None: 
            lat = location.lat
            lng = location.lng
            place_id = location.place_id
            label = "from my database"

        if location.address and location.country and location.zipcode and location.city != None: 
            address_string = str(location.address)+", "+str(location.zipcode)+", "+str(location.city)+", "+str(location.country)
            key = getattr(settings, 'GOOGLE_API_KEY', None)
            gmaps = googlemaps.Client(key)
            result = gmaps.geocode(address_string)[0]
            
            lat = result.get('geometry', {}).get('location', {}).get('lat', None)
            lng = result.get('geometry', {}).get('location', {}).get('lng', None)
            place_id = result.get('place_id', {})
            label = "from my api call"
            location.lat = lat
            location.lng =  lng
            location.place_id = place_id
            location.save()

        else: 
            result = ""
            lat = ""
            lng = ""
            place_id = ""
            label = "no call made"


        context = {
            'result':result,
            'location':location,
            'lat':lat, 
            'lng':lng, 
            'place_id':place_id, 
            'label':label
        }
        
        return render(request, self.template_name, context)
    
class DistanceView(View):
    template_name = "pages/distance.html"

    def get(self, request): 
        form = DistanceForm
        distances = Distances.objects.all()
        context = {
            'form':form,
            'distances':distances
        }

        return render(request, self.template_name, context)

    def post(self, request): 
        form = DistanceForm(request.POST)
        if form.is_valid(): 
            from_location = form.cleaned_data['from_location']
            from_location_info = Location.objects.get(name=from_location)
            from_address_string = str(from_location_info.address)+", "+str(from_location_info.zipcode)+", "+str(from_location_info.city)+", "+str(from_location_info.country)

            to_location = form.cleaned_data['to_location']
            to_location_info = Location.objects.get(name=to_location)
            to_address_string = str(to_location_info.address)+", "+str(to_location_info.zipcode)+", "+str(to_location_info.city)+", "+str(to_location_info.country)

            mode = form.cleaned_data['mode']
            now = datetime.now()
            key = getattr(settings, 'GOOGLE_API_KEY', None)
            gmaps = googlemaps.Client(key)
            calculate = gmaps.distance_matrix(
                    from_address_string,
                    to_address_string,
                    mode = mode,
                    departure_time = now
            )


            duration_seconds = calculate['rows'][0]['elements'][0]['duration']['value']
            duration_minutes = duration_seconds/60

            distance_meters = calculate['rows'][0]['elements'][0]['distance']['value']
            distance_kilometers = distance_meters/1000

            if 'duration_in_traffic' in calculate['rows'][0]['elements'][0]: 
                duration_in_traffic_seconds = calculate['rows'][0]['elements'][0]['duration_in_traffic']['value']
                duration_in_traffic_minutes = duration_in_traffic_seconds/60
            else: 
                duration_in_traffic_minutes = None

            
            obj = Distances(
                from_location = Location.objects.get(name=from_location),
                to_location = Location.objects.get(name=to_location),
                mode = mode,
                distance_km = distance_kilometers,
                duration_mins = duration_minutes,
                duration_traffic_mins = duration_in_traffic_minutes
            )

            obj.save()

        else: 
            print(form.errors)
        
        return redirect('distance')
    
class DisplayMapView(View): 
    template_name = "pages/display_map.html"
    apikey = getattr(settings, 'GOOGLE_API_KEY', None)
    def get(self,request): 
        context = {
            "key": DisplayMapView.apikey
        }

        return render(request, self.template_name, context)
    
class LocationListView(ListView):
    model = Location
    template_name = "pages/locations.html"
    
    def get_queryset(self):
        return (
            Location.objects.filter(creator=self.request.user)
        )

class LocationDetailView(DetailView):
    model = Location
    template_name = "locations/location_detail.html"

    def get(self, request, pk):
        location = Location.objects.get(pk=pk)
        
        
        # Once we have the address use it to get latitude and longitude from the API 
        if (location.address and location.country and location.zipcode and location.city != None) and (location.lat == None or location.lng == None or location.place_id == None): 
            print("here in detail view")
            address_string = str(location.address)+", "+str(location.zipcode)+", "+str(location.city)+", "+str(location.country)
            key = getattr(settings, 'GOOGLE_API_KEY', None)
            gmaps = googlemaps.Client(key)
            result = gmaps.geocode(address_string)[0]
            
            location.lat = result.get('geometry', {}).get('location', {}).get('lat', None)
            location.lng = result.get('geometry', {}).get('location', {}).get('lng', None)
            location.place_id = result.get('place_id', {})
        location.creator = str(self.request.user)

        location.save()
        context = {
            "location": location
        }
        return render(request, self.template_name, context)

class LocationCreateView(CreateView):
    model = Location
    fields = ['name', 'zipcode', 'city', 'country', 'address']
    template_name = "locations/location_form.html"
    #permission_required = 'location.add_location'

class LocationUpdateView(UpdateView):
    model = Location
    # Not recommended (potential security issue if more fields added)
    fields = ['name', 'zipcode', 'city', 'country', 'address']
    template_name = "locations/location_form.html"
    #permission_required = 'location.change_location'


class LocationDeleteView(DeleteView):
    model = Location
    success_url = reverse_lazy('locations')
    template_name = "locations/location_confirm_delete.html"
    #permission_required = 'location.delete_location'

    def form_valid(self, form):
        try:
            self.object.delete()
            return render(self.success_url)
        except Exception as e:
            return render(
                reverse("location-delete", kwargs={"pk": self.object.pk})
            )
        

class MapListView(ListView):
    model = Map
    template_name = "pages/maps.html"

    def get_queryset(self):
        return (
            Map.objects.filter(creator=self.request.user)
        )

class MapDetailView(DetailView):
    model = Map

    template_name = "maps/map_detail.html"
    apikey = getattr(settings, 'GOOGLE_API_KEY', None)
        
    def get(self, request, pk): 
        # Get the map and its locations
        map = Map.objects.get(pk=pk)
        map_locations = map.locations.all()

        map.creator = str(self.request.user)
        map.save()
        
        # Generate the starting point, waypoints and destination parrameters for API call
        origin = f'{map.starting_location.lat},{map.starting_location.lng}'
        dest = f'{map.dest_location.lat},{map.dest_location.lng}'
        way_points = []
        for location in map_locations:
            # check to make sure this isn't the starting or end point
            print("In for loop")
            if location != map.starting_location and location != map.dest_location:
                print("Location name: ", location.name)
                way_points.append(f'{location.lat},{location.lng}')

        print("origin: ", origin)
        print()
        print("way_points: ", way_points)
        print()
        print("dest: ", dest)


        locations = []        
        address_string = ""
        apikey = getattr(settings, 'GOOGLE_API_KEY', None)
        print("map_locations: ", map_locations)
        
      #  buildPath(self, request, pk)
        for location in map_locations:          
            data = {
                'lat': float(location.lat),
                'lng': float(location.lng),
                'name': location.name
            }
            locations.append(data)

        origin = json.dumps(origin)
        way_points = json.dumps(way_points)
        dest = json.dumps(dest)

        context = {
            "map": map,
            "origin": origin,
            "way_points": way_points,
            "dest": dest,
            'address': address_string,
            "key": MapDetailView.apikey
        }

        return render(request, self.template_name, context)
        

class MapCreateView(CreateView):
    model = Map
    #fields = ['name', 'starting_location', 'dest_location', 'locations']
    template_name = "maps/map_form.html"

    def get(self, request):
        context = {

localsights/templates/maps/map_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<style>
    body {
        background: linear-gradient(to bottom, #002466, #ffffff);
        color: white;
        padding: 0;
        margin: 0;
        font-family: 'Consolas', serif;
    }

    .container {
        padding-bottom: 20vw;
        padding: 3vw;
        text-align: left;
    }

    h1 {
        font-size: 3vw;
        font-weight: bold;
        margin-bottom: 20px;
    }

    p {
        font-size: 1.5vw;
        margin-bottom: 40px;
    }


    input[type="submit"] {
        background-color: #f77a7a;
        color: white;
        border: none;
        padding: 10px 20px;
        font-size: 15px;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        border-radius: 5px;
    }

    input[type="submit"]:hover {
        background-color: #f55454;
    }

</style>

<div class="container">
    <h1>Delete Map: {{ map.name }}</h1>
    <p>Are you sure you want to delete the Map?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete.">
    </form>
</div>
{% endblock %}

localsights/templates/maps/map_detail.html
{% extends 'base.html' %}


{% block content %}
<style>
    .mapholder {
        height: 25vh;
        /* Change the height to a percentage of the viewport height */
        width: 100%;
        /* Keep the width at 100% */
        margin-top: 20px;
        /* Optional: Add margin for spacing */
    }

    #map {
        height: 33vw;
        overflow: visible;
    }

    #ourtable3_wrapper {
        width: 98%;
        margin-left: 1%;
        margin-right: 1%;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .myTable {
        font-size: 12px;
        overflow: hidden;
        border-radius: 7px 7px 0 0;
        box-shadow: 0 0 20px rgba(0, 0, 0, .15);
    }

    .myTable th {
        background-color: #2D323E;
        color: white;
        font-weight: bold;
    }

    .myTable td,
    .myTable th {
        border: 0.01em solid #e3e2e2;
    }

    .myTable tr:nth-child(even) {
        background-color: #f9f8f8;
    }

    /* Formats the text*/
    #ourtable3_filter,
    #ourtable3_length,
    #ourtable3_info,
    #ourtable3_paginate {
        font-size: 12px;
        font-weight: bold;
        color: #333;
    }

    /* Formats the input fields*/
    #ourtable3_filter input,
    #ourtable3_length select {
        border: 1px solid rgb(3, 154, 204);
    }

    .pageholder,
    form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        width: 100%;
    }

    .titleholder,
    .linkholder {
        display: flex;
        margin-top: 10px;
        width: 98%;
        border-radius: 5px;
    }

    .ourbutton {
        margin-right: 10px;
        height: 30px;
        width: 100px;
        margin-left: 15px;
        margin-bottom: 20px;
        border-radius: 5px;

        background-color: rgb(0, 0, 80);
        color: white
    }

    .ourbutton:hover {
        margin-right: 10px;
        background-color: rgb(142, 142, 142);
        color: white
    }

    .form1 {
        width: 30%;
    }

    form {
        width: 100%;
    }

    .titleholder {
        display: 'flex';
        justify-content: 'space-between';
        align-items: center;
        height: 40px;
    }

    .linkholder {
        box-shadow: 0 0 20px rgba(0, 0, 0, .15);
        flex-direction: column;

    }


    .title {
        color: white;
        margin-left: 10px;
        font-weight: bold;
        font-size: 20px;
        font-family: 'Consolas', Tahoma, Geneva, Verdana, sans-serif;
    }

    .title2 {
        color: #333;
        margin-left: 10px;
        font-weight: bold;
        font-size: 15px;
        font-family: 'Consolas', Tahoma, Geneva, Verdana, sans-serif;
    }

    .linkbox {
        display: flex;
        width: 100%;
        height: 20px;
        justify-content: center;
        text-align: center;
        align-items: center;
        border-radius: 5px;
        box-shadow: 0 0 20px rgba(0, 0, 0, .15);


    }

    body {
        background: linear-gradient(to bottom, #002466, #ffffff);
        background-size: cover;
        color: #fff;
        padding: 0;
        margin: 0;
        font-family: 'Consolas', serif;
        overflow-x: hidden;
        /* Prevent horizontal scrolling */
    }

    /* Add button from map_details */
    .button-holder {
        margin-top: 21.5vw;
        left: 10%;
        text-align: center;
        /* Center the button horizontally */
        /* move botton to left */


    }

    .button-holder button {
        height: 50px;
        width: 150px;
        border-radius: 5px;
        background-color: #007bff;
        /* Blue color for the button */
        color: white;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        transition: background-color 0.3s ease;
        /* Smooth hover effect */
    }

    .button-holder button:hover {
        background-color: #0056b3;
        /* Darker blue on hover */
    }
</style>





<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

<script>

    let map

    function initMap() {
        var directionsService = new google.maps.DirectionsService();
        var directionsRenderer = new google.maps.DirectionsRenderer();

        const map = new google.maps.Map(document.getElementById("map"), {
            center: { lat: 38.4496, lng: -78.8689 },
            zoom: 8,
            mapId: "8433f60590734a15",
        });
        directionsRenderer.setMap(map);
        calculateAndDisplayRoute(directionsService, directionsRenderer);
    }

    function calculateAndDisplayRoute(directionsService, directionsRenderer) {
        var waypts = [];

        var origin = JSON.parse('{{origin|safe}}')
        var waypoints = JSON.parse('{{way_points|safe}}')
        var dest = JSON.parse('{{dest|safe}}')


        for (let i = 0; i < waypoints.length; i++) {
            waypts.push({
                location: waypoints[i],
                stopover: true,
            });
        }

        console.log(origin)
        console.log(waypts)
        console.log(dest)


        directionsService
            .route({
                origin: origin,
                destination: dest,
                waypoints: waypts,
                optimizeWaypoints: true,
                travelMode: google.maps.TravelMode.DRIVING,
            })
            .then((response) => {
                console.log(response)
                directionsRenderer.setDirections(response);

            })
            .catch((e) => window.alert("Directions request failed due to " + status));
    }
    // console.log(myList)

    /*    const map = new Map(document.getElementById("map"), {
            center: { lat: 38.4496, lng: -78.8689 },
            zoom: 8,
            mapId: "8433f60590734a15",
        });
        
       // console.log(typeof locations)
       // console.log(locations)
       // console.log(typeof locations[0].lat)
       // console.log(locations[0].lat)
       // console.log(locations[1])
       // console.log(locations[2])

        
        locations.forEach(function (location) {
            console.log(location)
            console.log(location.lat)
            console.log(location.lng)

            const marker = new AdvancedMarkerElement({
            position: { lat: location.lat, lng: location.lng },
            map: map,
            title: location.name,
          }); 
        })
        }
    
    */
    window.initMap = initMap
</script>


<div class="pageholder">
    <div class="titleholder">
        <div class="title"> Your Map's Details! </div>
    </div>

    <!-- <div class="linkholder">
      <table id="ourtable3" class="myTable m-3">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Address</th>
                <th>Zipcode</th>
                <th>City</th>
                <th>Country</th>
                <th>Geocode link</th>
            </tr>
        </thead>

        <tbody>
            {% for location in map.locations.all %}
            <tr>
                <td> {{location.id}} </td>
                <td> {{location.name}} </td>
                <td> {{location.address}} </td>
                <td> {{location.zipcode}} </td>
                <td> {{location.city}} </td>
                <td> {{location.country}} </td>
                <td> <a href="{% url 'geocoding' location.id %}"> Geocode!</a> </td>
            </tr>
            {% endfor%}
        </tbody>        
      </table>
    </div> -->

    <div class="linkholder">
        <div class="mapholder" style="width: 100%; height: 300px;">
            <div id="map"></div>

            <script async src="https://maps.googleapis.com/maps/api/js?key={{key}}&loading=async&callback=initMap">
            </script>




        </div>


    </div>



    <script>
        function openGoogleMaps() {
            const origin = encodeURIComponent('{{origin|safe}}');
            const destination = encodeURIComponent('{{dest|safe}}');
            const waypoints = encodeURIComponent('{{way_points|safe}}');

            const url = `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&waypoints=${waypoints}`;
            window.open(url, '_blank');
        }
    </script>


</div>

<div class="button-holder">
    <button onclick="openGoogleMaps()"><span>Get Directions</span></button>
</div>


{% endblock %}

localsights/templates/maps/map_form.html
{% extends "base.html" %}

{% block content %}
<style>
    body {
        background: linear-gradient(to bottom, #002466, #ffffff);
        color: white;
        padding: 0;
        margin: 0;
        font-family: 'Consolas', serif;
    }

    .container {
        padding-bottom: 20vw;
        padding: 2vw;
        text-align: left;
    }


    h1 {
        font-size: 3vw;
        font-weight: bold;
        margin-bottom: 20px;
    }

    form {

        padding: 20px;
        border-radius: 10px;
    }

    .button {
        background: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 15px;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        transform: skew(-21deg);
        margin-top: 20px;
        /* Add margin for spacing */
        position: relative;
        z-index: 1;
    }

    .button::before {
        content: '';
        position: absolute;
        top: 0;
        bottom: 0;
        right: 100%;
        left: 0;
        background: #002466;
        opacity: 0;
        z-index: -1;
        transition: all 0.5s;
    }

    .button:hover {
        color: #fff;
    }

    .button:hover::before {
        left: 0;
        right: 0;
        opacity: 1;
    }
</style>

<div class="container">
    <div class="sidebar">
        <!-- Sidebar content here -->
    </div>
    <h1>Create your map!</h1>
    <form method="post" class = "map-form">
        <p>
            <label for="id_name">Name:</label> <input type="text" name="name" maxlength="200" required="" id="id_name">
        </p>
        <p>
            <label for="id_starting_location">Starting location:</label> 
            <select name="starting_location"
                id="id_starting_location">
                {% if loc_list %}
                    {% for loc in loc_list %} 
                        <option value = "{{loc.id}}">{{ loc.name }}</option> 
                    {% endfor %}
                {% else %}
                    <option disabled>None</option>
                {% endif %}
            </select>
        </p>
        <p>
            <label for="id_dest_location">Dest location:</label> 
            <select name="dest_location" id="id_dest_location">
                {% if loc_list %}
                    {% for loc in loc_list %} 
                        <option value = "{{loc.id}}">{{ loc.name }}</option> 
                    {% endfor %} 
                {% else %}
                    <option disabled>None</option>
                {% endif %}
            </select>
            
        </p>
        <p>
            <label for="id_locations">Locations:</label>
            <select name="locations" required="" id="id_locations" multiple="">
                {% if loc_list %}
                    {% for loc in loc_list %} 
                        <option value = "{{loc.id}}">{{ loc.name }}</option> 
                    {% endfor %} 
                {% else %}
                <option disabled>None</option>
                {% endif %}
          </select>
        </p>
        <button type="submit" class="button" id="mapDetails">Submit</button>
    </form>
    <script>
        let form =  document.querySelector(".map-form");
        form.addEventListener("submit", (e) => {
            e.preventDefault();
            let formData = new FormData( form );
            let object = {};
            object.locations = [];
            formData.forEach((value, key) => {
                if (key == "locations") {
                    object.locations.push(value);
                } else {
                    object[key] = value
                }
            });
            
            let json = JSON.stringify(object);
            //console.log(json);
            fetch("/api/map",
            {
                headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
                },
                method: "POST",
                body: json
            })
            .then(async function(res){ 
                let j = await res.json();
                let id = j.id;
                window.top.location.href = "/maps/" + id;
            })
            .catch(function(res){ console.log(res) });
        });
    </script>
    
</div>
{% endblock %}