localsights/maps/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("home", HomeView.as_view(), name='home'),
    path("maps", MapView.as_view(), name='maps'),
    path("geocoding/<int:pk>", GeocodingView.as_view(), name='geocoding'),
    path("distance", DistanceView.as_view(), name='distance'),
    path("display_map", DisplayMapView.as_view(), name='display_map'),
    
]

localsights/users/urls.py
from django.urls import path

from localsights.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

localsights/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name Do Not Cover Name Patterns
    # Around the Globe.
    name = models.CharField(
        _("Name of User"), blank=True, max_length=255
    )

    def get_absolute_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.username}
        )

localsights/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {
            "duplicate_username": _(
                "This username has already been taken."
            )
        }
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(
            self.error_messages["duplicate_username"]
        )

localsights/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import (
    DetailView,
    RedirectView,
    UpdateView,
)

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These Next Two Lines Tell the View to Index
    #   Lookups by Username
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = [
        "name",
    ]

    # We already imported user in the View code above,
    #   remember?
    model = User

    # Send the User Back to Their Own Page after a
    #   successful Update
    def get_success_url(self):
        return reverse(
            "users:detail",
            kwargs={'username': self.request.user.username},
        )

    def get_object(self):
        # Only Get the User Record for the
        #   User Making the Request
        return User.objects.get(
            username=self.request.user.username
        )


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail",
            kwargs={"username": self.request.user.username},
        )


user_redirect_view = UserRedirectView.as_view()

localsights/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  User: {{ object.username }}
{% endblock title %}

{% block content %}
<style>
    body {
        background: linear-gradient(to bottom, #002466, #ffffff);
        color: white;
        padding: 0;
        margin: 0;
        font-family: 'Consolas', serif;
    }

    .container {
        padding: 4.5vw;
        text-align: left;
    }

    h2 {
        font-size: 3vw;
        font-weight: bold;
        margin-bottom: 20px;
    }

    p {
        font-size: 2vw;
        margin-bottom: 10px;
    }

    .button {
        background: #fff;
        border: none;
        padding: 10px 20px;
        font-size: 15px;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        transform: skew(-21deg);
        margin-top: 20px; /* Add margin for spacing */
        position: relative;
        z-index: 1;
    }

    .button::before {
        content: '';
        position: absolute;
        top: 0;
        bottom: 0;
        right: 100%;
        left: 0;
        background: #002466;
        opacity: 0;
        z-index: -1;
        transition: all 0.5s;
    }

    .button:hover {
        color: #fff;
    }

    .button:hover::before {
        left: 0;
        right: 0;
        opacity: 1;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ object.username }}</h2>
            {% if object.name %}
                <p>{{ object.name }}</p>
            {% endif %}
        </div>
    </div>

    {% if object == request.user %}
    <!-- Action buttons -->
    <div class="row">
        <div class="col-sm-12">
            <a class="button" href="{% url 'users:update' %}">My Info</a>
            <a class="button" href="{% url 'account_email' %}">E-Mail</a>
            <!-- Your Stuff: Custom user template urls -->
        </div>
    </div>
    <!-- End Action buttons -->
    {% endif %}
</div>
{% endblock content %}

localsights/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
  {{ user.username }}
{% endblock title %}

{% block content %}
<style>
    body {
        background: linear-gradient(to bottom, #002466, #ffffff);
        color: white;
        padding: 0;
        margin: 0;
        font-family: 'Consolas', serif;
    }

    h1 {
        font-size: 3vw;
        font-weight: bold;
        margin-bottom: 20px;
    }

    form {
        padding: 20px;
        border-radius: 10px;
    }

    .container {
        padding: 2vw;
        text-align: left;
    }

    .btn-primary {
        background-color: #6e82f5;
        color: white;
        border: none;
        padding: 10px 20px;
        font-size: 15px;
        font-weight: 600;
        text-transform: uppercase;
        cursor: pointer;
        border-radius: 5px;
    }

    .btn-primary:hover {
        background-color: #4854a5;
    }
</style>

<div class="container">
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}